name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  logger: ^2.6.2
  provider: ^6.1.5+1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_ui_auth: ^3.0.1
  firebase_ui_localizations: ^2.0.1
  intl_utils: ^2.8.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_intl:
  enabled: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/
